#tag::port[]
micronaut:
  server:
    port: 8081
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
#end::port[]
---
#tag::oauth2[]
micronaut:
  security:
    intercept-url-map:
      - pattern: /swagger-ui/**
        http-method: GET
        access: isAnonymous()
      - pattern: /swagger/**
        http-method: GET
        access: isAnonymous()
      - pattern: /**
        access: isAnonymous()
    enabled: true
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: 'http://localhost:8080/realms/myrealm/protocol/openid-connect/certs'
    oauth2:
      clients:
        keycloak:
          grant-type: password
          client-secret: 'R1QNUg2kXQ5S4OBOK0AW7ccg5g1N4YSP'
          client-id: 'realmtest'
          authorization:
            url: 'http://localhost:8080/realms/myrealm/protocol/openid-connect/auth'
    endpoints:
      logout:
        get-allowed: true
  openapi:
    views:
      spec: swagger-ui.enabled=true,swagger-ui.theme=flattop

datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    schema-generate: CREATE_DROP
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book-store
    username: postgres
    password: postgres
#end::oauth2[]
